// <auto-generated />
using FabricaDeChocolate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FabricaDeChocolate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Embalagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtdDisponivel")
                        .HasColumnType("int");

                    b.Property<int>("QtdMinima")
                        .HasColumnType("int");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Embalagens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "Amarelo",
                            QtdDisponivel = 200,
                            QtdMinima = 100,
                            Tamanho = "4x8"
                        },
                        new
                        {
                            Id = 2,
                            Cor = "Azul",
                            QtdDisponivel = 430,
                            QtdMinima = 100,
                            Tamanho = "5x10"
                        });
                });

            modelBuilder.Entity("FabricaDeChocolate.Data.Trufa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmbalagemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmbalagemId");

                    b.ToTable("Trufas");
                });

            modelBuilder.Entity("FabricaDeChocolate.Data.Trufa", b =>
                {
                    b.HasOne("Embalagem", "Embalagem")
                        .WithMany("Trufas")
                        .HasForeignKey("EmbalagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Embalagem");
                });

            modelBuilder.Entity("Embalagem", b =>
                {
                    b.Navigation("Trufas");
                });
#pragma warning restore 612, 618
        }
    }
}
